services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rails
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
